name: Other
description: Other issues (e.g. questions, discussions, documentation issues)
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! Use this for questions, discussions, documentation issues, or anything else that doesn't fit into the other categories.

  - type: input
    id: component
    attributes:
      label: Component(s)
      description: Which component(s) does this issue relate to?
      placeholder: e.g. go/pkg/otel/arrow_record, rust/src/lib.rs, collector/cmd/otelarrowcol, documentation
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      description: What type of issue is this?
      options:
        - Question
        - Documentation
        - Discussion
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0